### ISSUE TITLE
Connection handle

### ISSUE THREAD

**Issue by BulatSaif** [pauloborges/bluez#1]
I use hcitool and  gatttool to create connection with BLE device. Each time I get "Connection handle 64" 
`
sudo hcitool -i hci0 lecc --random C2:3C:E7:CC:FD:74
Connection handle 64
`
But I need Connection handle = 19.
Is it possible choose connection handle? I viewed code and did not understand where it generated.
Please, help me...

**Comment by pauloborges** [comment]
This is a very old fork of bluez.

You can try to get help from the developers at http://www.bluez.org/contact/.
